### ISSUE TITLE
Recompile to make compatible with 9.0.0

### ISSUE THREAD

**Issue by cucholix** [retronx-team/Alien-vs.-Predator-Gold-Switch#2]
Apps needs to be recompiled against the new libnx or else they won’t be able to detect button inputs, atmosphere will still give support for old libnx, but eventually it will be dropped in the future.

More info: https://github.com/Atmosphere-NX/Atmosphere/releases

**Comment by m4xw** [comment]
Why would u think I forgot it?
If you have immediate hurry, compile it yourself.
